name: "$(date:yyyyMMdd)$(Build.BuildId)"

trigger:
- main

variables:
  nodeModulesCache: $(System.DefaultWorkingDirectory)/node_modules

pool:
  name: default
  demands:
  - agent.name -equals MacBook-Pro-di-Jonathan

steps: 
- script: |    
    docker stop menu-frontend-container-frontend-1
    docker rm menu-frontend-container-frontend-1
    docker image rm menu-frontend-container-frontend
  continueOnError: true
  displayName: 'Clean current docker image'
- script: |        
    docker compose -p menu-frontend-container up  --detach
  displayName: 'Build and start container'