name: "$(date:yyyyMMdd)$(Build.BuildId)"

trigger:
- master

pool:
  name: default
  demands:
  - agent.name -equals MacBook-Pro-di-Jonathan

stages:
- stage: BuildVersion  
  jobs:   
    - job: Test             
      steps:
        - script: npm install
          displayName: 'Installa dipendenze'        
        - script: npm run test-ci
          displayName: 'Esegui test' 
      displayName: "Test versione"
    - job: Build   
      dependsOn: Test    
      steps:
        - script: npm install
          displayName: 'Installa dipendenze'        
        - script: npm run build
          displayName: 'Compila'              
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.SourcesDirectory)/dist/frontend-angular/browser/'
            publishLocation: 'pipeline'
          displayName: "Pubblica artefatto"        
  displayName: "Pubblicazione versione" 
    
