name: "$(date:yyyyMMdd)$(Build.BuildId)"

trigger:
- main

pool:
  name: default
  demands:
  - agent.name -equals MacBook-Pro-di-Jonathan

steps:
- script: |    
    npm install
    ng build
  displayName: 'npm install and build'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist/frontend-angular/browser/'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.BuildNumber).zip'
    replaceExistingArchive: true
  displayName: "Create zip package"
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.BuildNumber).zip'
    publishLocation: 'pipeline'
  displayName: "Publish zip package"
