name: "$(date:yyyyMMdd)$(Build.BuildId)"

trigger:
- main

pool:
  name: default
  demands:
  - agent.name -equals MacBook-Pro-di-Jonathan

steps:
- checkout: self
  clean: false 
- task: Cache@2
  inputs:
    key: 'npm | "$(Agent.OS)" | client/package-lock.json'
    restoreKeys: |
                npm | "$(Agent.OS)"
    path: $(nodeModulesCache)
  displayName: Cache Node modules
- script: |    
    npm install   
  displayName: 'Install node modules'
- script: |        
    ng build
  displayName: 'Build Angular app'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist/frontend-angular/browser/'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.BuildNumber).zip'
    replaceExistingArchive: true
  displayName: "Create zip package"
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.BuildNumber).zip'
    publishLocation: 'pipeline'
  displayName: "Publish zip package"
