name: "$(date:yyyyMMdd)$(Build.BuildId)"

trigger:
- main

variables:
  nodeModulesCache: $(System.DefaultWorkingDirectory)/node_modules

pool:
  name: default
  demands:
  - agent.name -equals MacBook-Pro-di-Jonathan

stages:
- stage: Build
  jobs:
  - job: BuildProject
    steps:
    - checkout: self
      clean: false 
    - script: |    
        npm install   
      displayName: 'Install node modules'     
  displayName: "Build project"

- stage: Test
  jobs:
  - job: RunTest
    steps:
    - script: |
        npm install
        npm test
    displayName: 'Test project'
  displayName: "Run tests"

- stage: DistributeLocally
  jobs:
  - job: DistributeLocally
    steps:
      - script: |
          ng build
        displayName: 'Build Angular app'
      - task: ArchiveFiles@2
        inputs:
          rootFolderOrFile: 'dist/frontend-angular/browser/'
          includeRootFolder: true
          archiveType: 'zip'
          archiveFile: '$(Build.BuildNumber).zip'
          replaceExistingArchive: true
        displayName: "Create zip package"
      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(Build.BuildNumber).zip'
          publishLocation: 'pipeline'
        displayName: "Publish zip package"
  displayName: "Distribute on local machine"

- stage: "Distribute_docker_repository"  
  jobs:
  - deployment: 
    environment: "Approval"
  - job: DistributeDockerRepos
    steps:
      - task: Docker@2
        inputs:
          containerRegistry: 'Docker Jonathan'
          repository: 'puntoclassic/menu-frontend-angular'
          command: 'buildAndPush'
          Dockerfile: '**/Dockerfile'
          tags: |      
            latest
  displayName: "Push on docker repository"
    




