name: "$(date:yyyyMMdd) ($(Build.BuildId))"

trigger:
- main

pool:
  name: default
  demands:
  - agent.name -equals MacBook-Pro-di-Jonathan

steps:
- script: |    
    echo "$(date:yyyyMMdd)_$(Build.BuildId).zip"
  displayName: 'Version code and id'
