name: "$(date:yyyyMMdd)$(Build.BuildId)"

trigger:
- main

variables:
  nodeModulesCache: $(System.DefaultWorkingDirectory)/node_modules

pool:
  name: default
  demands:
  - agent.name -equals MacBook-Pro-di-Jonathan

steps:
- checkout: self
  clean: false 
- script: |    
    docker stop menu-frontend-angular-frontend-1
    docker rm menu-frontend-angular-frontend-1
    docker image rm menu-frontend-angular-frontend-1 
  displayName: 'Clean current docker image'
- script: |        
    docker builder ip
  displayName: 'Build and start container'


