name: "$(date:yyyyMMdd)$(Build.BuildId)"

trigger:
- main

variables:
  nodeModulesCache: $(System.DefaultWorkingDirectory)/node_modules

pool:
  name: default
  demands:
  - agent.name -equals MacBook-Pro-di-Jonathan

steps:
- checkout: self
  clean: false 
- script: |    
    npm install   
  displayName: 'Install node modules'
- script: |        
    ng build
  displayName: 'Build Angular app'
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist/frontend-angular/browser/'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.BuildNumber).zip'
    replaceExistingArchive: true
  displayName: "Create zip package"
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.BuildNumber).zip'
    publishLocation: 'pipeline'
  displayName: "Publish zip package"
