name: "$(date:yyyyMMdd)$(Build.BuildId)"

trigger:
- main

pool:
  name: default
  demands:
  - agent.name -equals MacBook-Pro-di-Jonathan

steps:
- script: |    
    echo "$(Agent.JobName).zip"
  displayName: 'Version code and id'
