name: "$(date:yyyyMMdd)$(Build.BuildId)"

trigger:
- main


pool:
  name: default
  demands:
  - agent.name -equals MacBook-Pro-di-Jonathan

steps:
- checkout: self
  clean: false 
- task: Docker@2
  inputs:
    containerRegistry: 'Docker Jonathan'
    repository: 'puntoclassic / menu-frontend-angular'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildId) latest'
