name: "$(date:yyyyMMdd)$(Build.BuildId)"

trigger:
- main

pool:
  name: default
  demands:
  - agent.name -equals MacBook-Pro-di-Jonathan

stages:
- stage: BuildVersion  
  jobs:    
    - job:        
      steps:
        - script: npm install
          displayName: 'Installa dipendenze'        
        - script: npm build
          displayName: 'Compila'
  displayName: "Compila la versione"
