name: "$(date:yyyyMMdd)$(Build.BuildId)"

trigger:
- main

variables:
  nodeModulesCache: $(System.DefaultWorkingDirectory)/node_modules

pool:
  name: default
  demands:
  - agent.name -equals MacBook-Pro-di-Jonathan

stages:
- stage: Build
  jobs:
    - checkout: self
      clean: false 
    - script: |    
      npm install   
    displayName: 'Install node modules' 

- stage: Test
  jobs:
    - script: |
      npm test  

- stage: Distribute locally
  jobs:
    - script: |        
    ng build
  displayName: 'Build Angular app'
  - task: ArchiveFiles@2
    inputs:
      rootFolderOrFile: 'dist/frontend-angular/browser/'
      includeRootFolder: true
      archiveType: 'zip'
      archiveFile: '$(Build.BuildNumber).zip'
      replaceExistingArchive: true
    displayName: "Create zip package"
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.BuildNumber).zip'
      publishLocation: 'pipeline'
    displayName: "Publish zip package"

- stage: Distribute docker image
  jobs:
    - task: Docker@2
    inputs:
      containerRegistry: 'Docker Jonathan'
      repository: 'puntoclassic/menu-frontend-angular'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |      
        latest
  

