name: "$(date:yyyyMMdd)$(Build.BuildId)"

trigger:
- master

pool:
  name: default
  demands:
  - agent.name -equals MacBook-Pro-di-Jonathan

stages:
- stage: BuildVersion  
  jobs:    
    - job:        
      steps:
        - script: npm install
          displayName: 'Installa dipendenze'        
        - script: npm run build
          displayName: 'Compila'              
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.SourcesDirectory)/dist/frontend-angualar/browser/'
            publishLocation: 'pipeline'
          displayName: "Pubblica artefatto"
        
  displayName: "Compila la versione"
