name: "$(date:yyyyMMdd)$(Build.BuildId)"

trigger:
- master

pool:
  name: default
  demands:
  - agent.name -equals MacBook-Pro-di-Jonathan

stages:
- stage: test
  displayName: "Test di versione"
  jobs:   
    - job: test             
      steps:
        - script: npm install
          displayName: 'Installa dipendenze'        
        - script: npm run test-ci
          displayName: 'Esegui test' 
      displayName: "Test automatici"     
- stage: build
  dependsOn: Test
  condition: succeeded()
  displayName: "Compilazione versione"  
  jobs:    
    - job: compilazione
      steps:
        - script: npm install
          displayName: 'Installa dipendenze'        
        - script: npm run build
          displayName: 'Compila'              
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(Build.SourcesDirectory)/dist/'
            publishLocation: 'pipeline'
          displayName: "Pubblica artefatto" 
- stage: deploy 
  dependsOn: build
  condition: succeeded()
  displayName: "Deploy server test"
  jobs:
    - deployment: 
      environment: Production
      strategy:
        runOnce:
          deploy:
            steps:
              - script: aws s3 sync --delete public-read ./dist s3://besolution.menuangular/
                displayName: Pubblicazione su AWS S3
    
                      
          

