name: "$(date:yyyyMMdd)$(Build.BuildId)"

trigger: none

pool:
  name: default
  demands:
  - agent.name -equals MacBook-Pro-di-Jonathan

parameters:
  - name: configurations
    type: object
    default:
      - development
      - cliente1
      - cliente2

stages:  
- stage: test
  displayName: "Test di versione"
  jobs:   
    - job: test             
      steps:
        - script: npm install
          displayName: 'Installa dipendenze'        
        - script: npm run test-ci
          displayName: 'Esegui test' 
      displayName: "Test automatici"  
- stage: build 
  dependsOn: Test
  condition: succeeded()
  displayName: "Compilazione versione"  
  jobs:    
    - job: compilazione
      displayName: "Compilazione"
      steps:
        - script: npm install
          displayName: 'Installa dipendenze'  
        - ${{ each configuration in parameters.configurations }}:      
          - template: build-configuration.yml
            parameters:
              configuration: ${{configuration}} 
        

  
     
                      
          

