parameters: 
- name: configuration
  type: string


steps:
  - script: npm run build -- --configuration=${{parameters.configuration}} --output-path=dist/${{parameters.configuration}}
    displayName: 'Compila ${{parameters.configuration}}'              
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.SourcesDirectory)/dist/${{parameters.configuration}}'  
      artifact: $(Build.BuildNumber)_${{parameters.configuration}}       
      publishLocation: 'pipeline'
    displayName: "Pubblica artefatto per $(Build.BuildNumber)_${{parameters.configuration}} "