parameters: 
- name: configuration
  type: string

jobs:
  job: build
  displayName: "Build configuration ${{parameters.configuration}}"
  steps:
    - script: npm run build -- --configuration=${{parameters.configuration}} --output-path=dist/${{parameters.configuration}}
      displayName: 'Compila'              
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Build.SourcesDirectory)/dist/${{parameters.configuration}}'  
        artifact: "$(date:yyyyMMdd)$(Build.BuildId)_${{parameters.configuration}}"          
        publishLocation: 'pipeline'
      displayName: "Pubblica artefatto"