name: 'Compila applicazione'
description: 'Compila applicazione Angular creando il pacchetto di distribuzione'
runs:
  using: 'composite'
  steps:
    - name: Install dependencies
      run: npm install
      shell: bash
    - name: Build version
      run: npm run build
      shell: bash