name: "Test and deploy"
run-name: "Test and deploy Build ${{github.run_number}}"

on: [workflow_dispatch]

jobs:
  integrate:
    name: Integrate new features/bug fixings
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install 
      - name: Execute tests
        run: npm run test-ci  
  delivery:    
    name: Create package for delivery
    needs: integrate
    runs-on: self-hosted
    environment: production
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install 
      - name: Build version
        run: npm run build  
  deploy-test-server:    
    name: Deploy to test server
    needs: integrate
    runs-on: self-hosted
    environment: production
    steps:
      - name: Upload to test server
        run: echo ""
       