name: "Test and deploy"
run-name: "Test and deploy build ${{$(date +'%Y%m%d')+"."+github.run_id}}"

on: [workflow_dispatch]
env:
  build_code: ${{$(date +'%Y%m%d')+"."+github.run_id}}

jobs:
  integrate:
    name: Integrate new features/bug fixings
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3      
      - name: Install dependencies
        run: npm install 
      - name: Execute tests
        run: npm run test-ci        
  delivery:    
    name: Create package for delivery
    needs: integrate
    runs-on: self-hosted
    environment: production
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3     
      - name: Install dependencies
        run: npm install 
      - name: Build version
        run: npm run build  
      - name: Generate package
        uses: actions/upload-artifact@v3
        with:
          name: "build_${{$build_code}}"
          path: dist/dev/
  deploy-test-server:    
    name: Deploy to test server
    needs: delivery
    runs-on: self-hosted
    environment: test-server
    steps:
      - name: Get Build package
        uses: actions/download-artifact@v3
        with:
          name: "build_${{$build_code}}"
          path: ./build_${{$build_code}}
      - name: Upload to test-server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          local-dir: ./build_${{$build_code}}/
          dangerous-clean-slate: true
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
      
       