name: "Test and deploy"
run-name: "Test and deploy Build ${{github.run_number}}"

on: [workflow_dispatch]

jobs:
  integrate:
    name: Integrate new features/bug fixings
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3      
      - name: Install dependencies
        run: npm install 
      - name: Execute tests
        run: npm run test-ci        
  delivery-test:    
    needs: integrate    
    uses: puntoclassic/menu-frontend-angular/.github/workflows/ng-build.yml@master
  delivery-cliente1:    
    needs: integrate    
    uses: puntoclassic/menu-frontend-angular/.github/workflows/ng-build.yml@master  
    with:
      configuration: cliente1
      output-path: dist/cliente1   
  delivery-cliente2:    
    needs: integrate    
    uses: puntoclassic/menu-frontend-angular/.github/workflows/ng-build.yml@master  
    with:
      configuration: cliente2
      output-path: dist/cliente2    
  deploy-test-server:    
    name: Deploy to test server
    needs: delivery-test
    environment: test-server
    runs-on: self-hosted
    steps:
      - name: Get Build package
        uses: actions/download-artifact@v3
        with:
          name: "Build_development_${{github.run_number}}"
          path: ./Build_${{github.run_number}}
      - name: Upload to test-server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          local-dir: ./Build_${{github.run_number}}/
          dangerous-clean-slate: true
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
      
       