name: "Test and deploy"
run-name: "Test and deploy Build ${{github.run_number}}"

on: [workflow_dispatch]

jobs:
  integrate:
    name: Integrate new features/bug fixings
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3      
      - name: Install dependencies
        run: npm install 
      - name: Execute tests
        run: npm run test-ci  
  delivery:    
    name: Create package for delivery
    needs: integrate
    runs-on: self-hosted
    environment: production
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3     
      - name: Install dependencies
        run: npm install 
      - name: Build version
        run: npm run build  
      - name: Generate package
        uses: actions/upload-artifact@v3
        with:
          name: "Build_${{github.run_number}}"
          path: dist/frontend-angular/browser/
  deploy-test-server:    
    name: Deploy to test server
    needs: delivery
    runs-on: self-hosted
    environment: test-server
    steps:
      - name: Get Build package
        uses: actions/download-artifact@v3
        with:
          name: "Build_${{github.run_number}}"
      
       