name: "Test and deploy (multi-delivery)"
run-name: "Test and deploy build ${{github.run_id}}"

on: [workflow_dispatch] 

jobs:
  init:
    runs-on: self-hosted
    outputs:
        version-code: ${{github.run_id}}
    steps:
        - name: Init params
          id: initstep
          run: echo "Init params" 
  integrate:
    needs: init
    name: Integrate new features/bug fixings
    runs-on: self-hosted
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3      
      - name: Install dependencies
        run: npm install 
      - name: Execute tests
        run: npm run test-ci        
  delivery-test:    
    needs: integrate    
    uses: puntoclassic/menu-frontend-angular/.github/workflows/ng-build.yml@master
    with:
      configuration: production
  delivery-cliente1:    
    needs: integrate    
    uses: puntoclassic/menu-frontend-angular/.github/workflows/ng-build.yml@master  
    with:
      configuration: cliente1
      output-path: dist/cliente1  
      version-code: ${{needs.init.outputs.version_code}}
  delivery-cliente2:    
    needs: integrate    
    uses: puntoclassic/menu-frontend-angular/.github/workflows/ng-build.yml@master  
    with:
      configuration: cliente2
      output-path: dist/cliente2    
      version-code: ${{needs.init.outputs.version_code}}
  deploy-test-server:    
    name: Deploy to test server
    needs: delivery-test
    environment: test-server
    runs-on: self-hosted
    steps:
      - name: Get Build package
        uses: actions/download-artifact@v3
        with:
          name: "build_production_${{needs.init.outputs.version_code}}"
          path: ./build_${{needs.init.outputs.version_code}}
      - name: Upload to test-server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          local-dir: ./build_${{needs.init.outputs.version_code}}/
          dangerous-clean-slate: true
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
      
       