name: "Test and deploy"
run-name: "Test and deploy build ${{github.run_number}}"

on: [workflow_dispatch]

jobs:
  init:
    name: Init params for workflow
    runs-on: self-hosted
    outputs:
        version-code: ${{steps.initstep.outputs.version-code}}
    steps:
        - name: Init params
          id: initstep
          run: echo "::set-output name=version-code::$(date)+"."+${{github.run_number}}" 
        - name: Print new version code
          run: echo "${{steps.initstep.outputs.version-code}}"
  
      
       