name: "Test and deploy"
run-name: "Test and deploy build ${{github.run_number}}"

on: [workflow_dispatch]

jobs:
  init:
    name: Init params for workflow
    runs-on: self-hosted
    outputs:
        version-code: ${{steps.initstep.outputs.version-code}}
    steps:
        - name: Init params
          id: initstep
          run: echo "name=version-code::$(date+'%Y%m%d').${{github.run_number}}" >> $GITHUB_OUTPUT
        - name: Print new version code
          run: echo "${{steps.initstep.outputs.version-code}}"
  
       
       