name: "Angular build specific configuration"

on: 
  workflow_call:
    inputs: 
      version-code: 
        default: ${{github.run_id}}
        type: string
      configuration:
        default: development
        type: string
      output-path:
        default: dist/dev
        type: string
jobs:  
  pack:    
    name: Create package
    runs-on: self-hosted  
    steps:      
      - name: Check out the repo
        uses: actions/checkout@v3     
      - name: Install dependencies
        run: npm install  
      - name: Build version
        run: npm run build -- --configuration=${{inputs.configuration}} --output-path=${{inputs.output-path}}
      - name: Generate package
        uses: actions/upload-artifact@v3
        with:
          name: "build_${{inputs.configuration}}_${{inputs.version-code}}"
          path: ${{inputs.output-path}}
      
  
      
       