name: "Upload S3"
run-name: "Deploy to S3 ${{github.run_number}}"

on: [workflow_dispatch]

jobs:  
  sync-aws-s3:
    name: Sincronizza con S3
    runs-on: self-hosted
    steps:      
      - name: Sincronizza con s3
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 sync --delete --acl public-read dist/development s3://besolution.menuangular/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-1"
  
      
       